function tedavidevamf()
    for i, player in ipairs(getElementsByType('player')) do
    setElementData(player, "sakin:data", false)
    end
    exports.global:takeMoney(source, 2500)
    outputChatBox("[+] #ffffffTedavi oldunuz.[-2500]", source, 0, 255, 0, true)
    setElementRotation(source, 0, 0, 330)
    setElementPosition(source, 293.052734375, 180.3134765625, 1007.171875)
    setElementHealth(source, 100)
    toggleControl(source, "jump", true)
    toggleControl(source, "sprint", true)
    toggleControl(source, "backwards", true)
    toggleControl(source, "walk", true)
    toggleControl(source, "forwards", true)
    toggleControl(source, "fire", true)
    toggleControl(source, "left", true)
    toggleControl(source, "right", true)
    toggleControl(source, "crouch", true)
    setCameraTarget(source, source)
    setElementVisibleTo(source, getRootElement(), true)
    setElementAlpha(source, 255)
end
addEvent("tedavi:devam", true)
addEventHandler("tedavi:devam", getRootElement(), tedavidevamf)