streams = {
    { "Radio Off", "" },
	{ "Metro FM", "http://provisioning.streamtheworld.com/pls/METRO_FMAAC.pls" },
	{ "Banko FM", "http://banko.netradyom.com:11148/" },
	{ "Super FM", "http://7469.live.streamtheworld.com:80/SUPER_FMAAC_SC" },
	{ "Mydonese FM", "http://provisioning.streamtheworld.com/pls/RADIO_MYDONOSEAAC.pls" },
	{ "iHolla FM", "http://ghost.wavestreamer.com:8421/listen.pls?sid=1" },
	{ "InkedRap FM", "http://listen.radionomy.com/inkedrap.m3u" },
	{ "NRJ Rap FR", "http://mp3.live.tv-radio.com/nrj_rap_fr/all/nrj_145338.mp3" },
	{ "NRJ Rap US", "http://mp3.live.tv-radio.com/nrj_rap_us/all/nrj_144854.mp3" },
	{ "A2R Rap US", "http://listen.radionomy.com/a2r-rap-us.m3u" },
	{ "Reggae FM", "http://listen.radionomy.com/a-reggae-fm-web.m3u" },
	{ "Classic FM", "http://listen.radionomy.com/abacusfm-bach.m3u" },
	{ "Arabic Radio", "http://yp.shoutcast.com/sbin/tunein-station.pls?id=157783" },
	{ "Rock Radio 1", "http://87.98.146.216/castcontrol/playlist.php?port=8000" },
	{ "Redneck Radio 101", "http://red.neostreams.info/auto/tunein.php/rjacks00/playlist.pls" },
	{ "BBC Radio 1 Extra", "http://www.bbc.co.uk/radio/listen/live/r1x_aaclca.pls" },
	{ "Pink FM", "http://yp.shoutcast.com/sbin/tunein-station.pls?id=89765" },
}